---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: pii-demo
  labels:
    app: mysql-server
type: Opaque
data:
  mysql_root_password: Rm1qdWYzdVV6OWc4dFQyVGFDcHlSYTNuQTZWOQ==
  mysql_database: cGlpX2RlbW8=
  mysql_user: cGlpX3VzZXI=
  mysql_password: Rm1qdWYzdVV6OWc4dFQyVGFDcHlSYTNuQTZWOQ==
