---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-iam-cloudwatch
  namespace: monitoring
  labels:
    app: grafana
type: Opaque
data:
  GRAFANA_IAM_ACCESS_KEY: Y2hhbmdlbWU=
  GRAFANA_IAM_SECRET_KEY: Y2hhbmdlbWU=
