---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-influxdb
  namespace: monitoring
  labels:
    app: grafana
type: Opaque
data:
  INFLUXDB_USERNAME: c3BlZWR0ZXN0
  INFLUXDB_PASSWORD: aDRHMWdBOW5RS2J0MzNONERmeEd4YzFmTmM2dw==
