---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: speedtest
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8086'
  labels:
    app: influxdb
spec:
    selector:
      app: influxdb
    type: LoadBalancer
    ports:
      - name: influxdb
        port: 8086
        targetPort: 8086
    loadBalancerIP: 10.11.1.55
...
