---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-speedtest-influxdb
  namespace: speedtest
  labels:
    app: influxdb
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2048Mi
...
