---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mikrotik-exporter-conf
  namespace: monitoring
  labels:
    app: mikrotik-exporter
data:
  device1: mikrotik
  address1: 10.11.1.1
  user1: prometheus
  device2: mikrotik
  address2: 10.11.1.11
  user2: prometheus
