---
apiVersion: v1
kind: Service
metadata:
  name: mikrotik-exporter
  namespace: monitoring
  labels:
    app: mikrotik-exporter
spec:
  selector: 
    app: mikrotik-exporter
  type: NodePort  
  ports:
    - port: 9436
      targetPort: 9436
---
apiVersion: v1
kind: Service
metadata:
  name: mikrotik-lte-exporter
  namespace: monitoring
  labels:
    app: mikrotik-lte-exporter
spec:
  selector:
    app: mikrotik-lte-exporter
  type: NodePort
  ports:
    - port: 9437
      targetPort: 9436
