---
apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9617'
  labels:
    app: pihole-exporter
spec:
  selector: 
    app: pihole-exporter
  type: ClusterIP
  ports:
    - port: 9617
      protocol: TCP
      targetPort: 9617
...
